### ISSUE TITLE
Name of package clashes with pydb debugger

### ISSUE THREAD

**Issue by goerz** [asrp/pyzdb#1]
The name of this package clashes with the python debugger of the same name (http://bashdb.sourceforge.net/pydb/). While that package is deprecated, it is still registered with the Python Package Index. Therefore, you would not be able to make your package pip-installable (`pip install pydb` will install the debugger). I would strongly advise to rename this package.

**Comment by asrp** [comment]
Thanks again for pointing this out! I'm glad you caught this early on.

I'm open to name suggestion (anyone's free to add to this issue). Otherwise, I'll just pick something random.

**Comment by gmcclins** [comment]
pysqdb?

**Comment by simonpacis** [comment]
pyzdb (for ZeroMQ)

**Comment by asrp** [comment]
Alright, I think pyzdb it is then. Thanks for your suggestions.
