### ISSUE TITLE
"pyzdb" on Russian language sound like "f*ckin liar"

### ISSUE THREAD

**Issue by xevin** [asrp/pyzdb#2]

**Comment by asrp** [comment]
Yikes! Thanks for reporting this. Language is such a minefield.

Although the readme does clearly state that its pronounced "pies" (as in Python) and *not* "peas". But having it written out probably doesn't help...

I'm not sure if anything will be done about this one.

**Comment by asrp** [comment]
Since there hasn't been any more comment on this, I will leave the project name as is.

**Comment by asrp** [comment]
Since there hasn't been any more comment on this, I will leave the project name as is.
